# Generated by Django 5.0.9 on 2025-01-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAcc",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("backAcc", models.FloatField(blank=True, null=True)),
                ("liveAcc", models.FloatField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("MktCap", models.FloatField(blank=True, null=True)),
                ("upper_95", models.FloatField(blank=True, null=True)),
                ("lower_95", models.FloatField(blank=True, null=True)),
                ("upper_95O", models.FloatField(blank=True, null=True)),
                ("lower_95O", models.FloatField(blank=True, null=True)),
                ("upper_95C", models.FloatField(blank=True, null=True)),
                ("lower_95C", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "DailyAcc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyAcc",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("backAcc", models.FloatField(blank=True, null=True)),
                ("liveAcc", models.FloatField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("MktCap", models.FloatField(blank=True, null=True)),
                ("upper_95", models.FloatField(blank=True, null=True)),
                ("lower_95", models.FloatField(blank=True, null=True)),
                ("upper_95O", models.FloatField(blank=True, null=True)),
                ("lower_95O", models.FloatField(blank=True, null=True)),
                ("upper_95C", models.FloatField(blank=True, null=True)),
                ("lower_95C", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "MonthlyAcc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PredsDaily",
            fields=[
                ("symbol", models.CharField(max_length=10)),
                ("date", models.DateField(primary_key=True, serialize=False)),
                (
                    "pred",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("pred_sign", models.IntegerField(blank=True, null=True)),
                (
                    "actual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("actual_sign", models.IntegerField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("pred_open", models.FloatField(blank=True, null=True)),
                ("pred_close", models.FloatField(blank=True, null=True)),
                ("actual_open", models.FloatField(blank=True, null=True)),
                ("actual_close", models.FloatField(blank=True, null=True)),
                ("pred_open_sign", models.IntegerField(blank=True, null=True)),
                ("pred_close_sign", models.IntegerField(blank=True, null=True)),
                ("actual_open_sign", models.IntegerField(blank=True, null=True)),
                ("actual_close_sign", models.IntegerField(blank=True, null=True)),
                ("inUpper", models.BooleanField(blank=True, null=True)),
                ("inLower", models.BooleanField(blank=True, null=True)),
                ("Above", models.BooleanField(blank=True, null=True)),
                ("Below", models.BooleanField(blank=True, null=True)),
                ("Perfect", models.BooleanField(blank=True, null=True)),
                ("inUpperO", models.BooleanField(blank=True, null=True)),
                ("inLowerO", models.BooleanField(blank=True, null=True)),
                ("PerfectO", models.BooleanField(blank=True, null=True)),
                ("inUpperC", models.BooleanField(blank=True, null=True)),
                ("inLowerC", models.BooleanField(blank=True, null=True)),
                ("PerfectC", models.BooleanField(blank=True, null=True)),
                ("AboveO", models.BooleanField(blank=True, null=True)),
                ("BelowO", models.BooleanField(blank=True, null=True)),
                ("AboveC", models.BooleanField(blank=True, null=True)),
                ("BelowC", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "PredsDaily",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PredsMonthly",
            fields=[
                ("symbol", models.CharField(max_length=10)),
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("pred_open", models.FloatField(blank=True, null=True)),
                ("pred_close", models.FloatField(blank=True, null=True)),
                ("pred_open_sign", models.IntegerField(blank=True, null=True)),
                ("pred_close_sign", models.IntegerField(blank=True, null=True)),
                ("actual_open", models.FloatField(blank=True, null=True)),
                ("actual_close", models.FloatField(blank=True, null=True)),
                ("actual_open_sign", models.IntegerField(blank=True, null=True)),
                ("actual_close_sign", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "PredsMonthly",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PredsWeekly",
            fields=[
                ("symbol", models.CharField(max_length=10)),
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("pred_open", models.FloatField(blank=True, null=True)),
                ("pred_close", models.FloatField(blank=True, null=True)),
                ("pred_open_sign", models.IntegerField(blank=True, null=True)),
                ("pred_close_sign", models.IntegerField(blank=True, null=True)),
                ("actual_open", models.FloatField(blank=True, null=True)),
                ("actual_close", models.FloatField(blank=True, null=True)),
                ("actual_open_sign", models.IntegerField(blank=True, null=True)),
                ("actual_close_sign", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "PredsWeekly",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WeeklyAcc",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("backAcc", models.FloatField(blank=True, null=True)),
                ("liveAcc", models.FloatField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("MktCap", models.FloatField(blank=True, null=True)),
                ("upper_95", models.FloatField(blank=True, null=True)),
                ("lower_95", models.FloatField(blank=True, null=True)),
                ("upper_95O", models.FloatField(blank=True, null=True)),
                ("lower_95O", models.FloatField(blank=True, null=True)),
                ("upper_95C", models.FloatField(blank=True, null=True)),
                ("lower_95C", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "WeeklyAcc",
                "managed": False,
            },
        ),
    ]
